### ISSUE TITLE
Why did AFQP_SECURE_SOCKETS_Threadsafe_SameSocketDifferentTasks fail?

### ISSUE THREAD

**Issue by tu-thai** [gnomons-sw/amazon-freertos#5] opened 2021-05-28 09:15 UTC
Use e2 studio debug to examine why AFQP_SECURE_SOCKETS_Threadsafe_SameSocketDifferentTasks failed.

**Comment by Wolveries** [comment] 2021-06-02 04:18
I can trace the call hierarchy of AFQP_SECURE_SOCKETS_Threadsafe_SameSocketDifferentTasks as follows:

AFQP_SECURE_SOCKETS_Threadsafe_SameSocketDifferentTasks
       -> prvSOCKETS_Threadsafe_SameSocketDifferentTasks()
            -> SOCKETS_Recv(): the return value is NG (-29184)
                 -> TLS_Recv()
                      -> mbedtls_ssl_read()
                            -> mbedtls_ssl_read_record()
                                 -> ssl_get_next_record()
                                       -> mbedtls_ssl_fetch_input()
                                            -> f_recv()
                                                f_recv() is assigned to prvNetworkRecv() by TLS_Connect() -> mbedtls_ssl_set_bio()
                                                   -> prvNetworkRecv()
                                                       -> R_WIFI_SX_ULPGN_ReceiveSocket()

  R_WIFI_SX_ULPGN_ReceiveSocket() does not have any return value as (-29184).
  I search and find a value of mbedtls library which matches the value: MBEDTLS_ERR_SSL_INVALID_RECORD (-0x7200)
  Then I suspect ssl_get_next_record() returns that value.

 However, I cannot reproduce the failure.
 It depends on the network.
 This time it is MBEDTLS_ERR_SSL_CONN_EOF.
 It is returned by mbedtls_ssl_fetch_input() -> this will spread up to mbedtls_ssl_read_record().
 At this point, mbedtls_ssl_read() will return 0.
`            if( ( ret = mbedtls_ssl_read_record( ssl, 1 ) ) != 0 )
            {
                if( ret == MBEDTLS_ERR_SSL_CONN_EOF )
                    return( 0 );

                MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_ssl_read_record", ret );
                return( ret );
            }`

   => And SOCKETS_Recv() returns 0.
   But I don't know why this failed:

`TEST_ASSERT_NOT_EQUAL_MESSAGE( 0, xReturned, "Timeout occurred" );`

**Closed** 2021-06-02 08:50 UTC
Labels: question
